export const dom= {
  htmlBodyElement: document.querySelector('body'),
  htmlMainElement: document.querySelector('.dashboard'),
  addClientModal: document.getElementById('add-client-modal'),
  addClientModalCloseButton: document.querySelector('.add-client-modal__close-btn'),
  addClientForm: document.getElementById('addClientForm'),
  appointmentForm: document.getElementById('appointment-form'),
  clientsSection: document.getElementById('clients-section'),
  clientsContainer: document.getElementById('clients-section__content'),
  clientsActionsContainer: document.getElementById('add-client-btn-container'),
  appointmentsContainer: document.getElementById('appointments-section__content'),
  appointmentClientsSelect: document.getElementById('appointment-clients'),
  appointmentsList: document.getElementById('appointments-section__list'),
  dateInput: document.getElementById('client-last_visit'),
  clientsSearchInput: document.getElementById('search-input'),
  clientsSortSelect: document.getElementById('sort-clients'),
};
