export const dom= {
  htmlBodyElement: document.querySelector('body'),
  htmlMainElement: document.querySelector('.dashboard'),
  addClientModal: document.getElementById('add-client-modal'),
  addClientModalCloseButton: document.querySelector('.add-client-modal__close-btn'),
  addClientForm: document.getElementById('addClientForm'),
  appointmentForm: document.getElementById('appointment-form'),
  clientsSection: document.getElementById('clients-section'),
  clientsContainer: document.getElementById('clients-section__content'),
  clientsActionsContainer: document.getElementById('add-client-btn-container'),
  appointmentsContainer: document.getElementById('appointments-section__content'),
  appointmentClientsSelect: document.getElementById('appointment-clients'),
  appointmentsList: document.getElementById('appointments-section__list'),
  appointmentModal: document.getElementById('appointment-modal'),
  dateInput: document.getElementById('client-last_visit'),
  clientsSearchInput: document.getElementById('search-input'),
  clientsSortSelect: document.getElementById('sort-clients'),
  appointmentSearchInput: document.getElementById('search-appointments-input'),
  appointmentSortSelect: document.getElementById('sort-appointments'),
  appointmentFiltersPopupOptionClientSelect: document.getElementById('appointments-filters-popup__option-client'),
  appointmentsFiltersPopup: document.getElementById('appointments-filters-popup'),
  appointmentsFiltersButton: document.getElementById('filter-btn'),
  appointmentsFiltersPopupOnlyFutureLabel: document.getElementById('appointments-filters-popup__label-only-future'),
  appointmentsFiltersPopupDateFromSelector: document.getElementById('appointments-filters-popup__dates-input-from'),
  appointmentsFiltersPopupDateToSelector: document.getElementById('appointments-filters-popup__dates-input-to'),
  appointmentsFiltersPopupResetButton: document.getElementById('appointments-filters-popup__reset-filters-button'),
  appointmentsFiltersPopupOnlyFutureCheckbox: document.getElementById('appointments-filters-popup__option-only-future'),
};
